DELIMITER $$
CREATE FUNCTION AGE_F (VICTIM_AGE INTEGER) 
RETURNS VARCHAR(20)
DETERMINISTIC
BEGIN  
	 DECLARE AGE_GROUP VARCHAR(20);
	 IF VICTIM_AGE BETWEEN "0" AND "12" THEN
		    SET  AGE_GROUP =  "KIDS";
	ELSEIF VICTIM_AGE BETWEEN "13" AND "23" THEN  
			SET AGE_GROUP = "TEENAGE";  
	ELSEIF VICTIM_AGE BETWEEN "24" AND "35" THEN  
			SET AGE_GROUP = "MIDDLE AGE";  
	ELSEIF VICTIM_AGE BETWEEN "36" AND "55" THEN   
		SET AGE_GROUP = "ADULTS";
	ELSEIF VICTIM_AGE BETWEEN "56" AND "120" THEN   
		SET AGE_GROUP = "OLD"; 
		END IF;  
		RETURN (AGE_GROUP);  
END;