DELIMITER $$ 
CREATE PROCEDURE CRIME_P()
BEGIN
	INSERT INTO CRIME.CRIME_T (
	REPORT_NO,
    INCIDENT_TIME,
    COMPLAINT_TYPE,
    CCTV_FLAG,
    PRECINCT_CODE,
    AREA_CODE,
    AREA_NAME,
	CCTV_COUNT,
	POPULATION_DENSITY,
    ROUNDS_PER_DAY,
    CRIME_CODE,
    CRIME_TYPE,
    WEAPON_CODE,
    WEAPON_DESC,
    CASE_STATUS_CODE,
    CASE_STATUS_DESC,
    VICTIM_CODE,
    VICTIM_NAME,
    VICTIM_SEX,
    VICTIM_AGE,
    WAS_VICTIM_ALONE,
    IS_VICTIM_INSURED,
    OFFENDER_CODE,
    OFFENDER_NAME,
    OFFENDER_SEX,
    OFFENDER_AGE,
    REPEATED_OFFENDER,
    NO_OF_OFFENCES,
    OFFENDER_RELATION,
    OFFICER_CODE,
    OFFICER_NAME,
    OFFICER_SEX,
    AVG_CLOSE_DAY,
    WEEK_NUMBER
	) SELECT * FROM CRIME.TEMP_T;
END;

-- CALL CRIME_P();
