DELIMITER $$
CREATE PROCEDURE LOCATION_P()
BEGIN
	INSERT INTO LOCATION_T (
        AREA_CODE,
        AREA_NAME,
        CCTV_COUNT,
        POPULATION_DENSITY,
        ROUNDS_PER_DAY
    )
    SELECT DISTINCT 
	    AREA_CODE,
        AREA_NAME,
        CCTV_COUNT,
        POPULATION_DENSITY,
        ROUNDS_PER_DAY
	FROM CRIME_T WHERE AREA_CODE NOT IN (SELECT DISTINCT AREA_CODE FROM LOCATION_T);
END;
