DELIMITER $$
CREATE PROCEDURE OFFICER_P()
BEGIN
    INSERT INTO  OFFICER_T (
       OFFICER_CODE,
       OFFICER_NAME,
       OFFICER_SEX,
	   AVG_CLOSE_DAY,
	   PRECINCT_CODE
	) 
    SELECT DISTINCT 
	     OFFICER_CODE,
         OFFICER_NAME,
         OFFICER_SEX,
	     AVG_CLOSE_DAY,
	     PRECINCT_CODE
	FROM CRIME_T WHERE  OFFICER_CODE NOT IN (SELECT DISTINCT   OFFICER_CODE FROM OFFICER_T);
END;

-- CALL OFFICER_P();
