CREATE VIEW REP_VICT_V AS
    SELECT 
         REP.REPORT_NO,
	     REP.INCIDENT_TIME,
         REP.OFFENDER_RELATION,
         REP.CRIME_TYPE,
	     VICT.VICTIM_CODE,
         VICT.VICTIM_AGE
    FROM REPORT_T REP
        JOIN VICTIM_T VICT ON 
            REP.VICTIM_CODE = VICT.VICTIM_CODE
    