CREATE VIEW REP_LOC_OFF_V AS
    SELECT 
         LOC.AREA_CODE,
         LOC.AREA_NAME,
         LOC.CCTV_COUNT,
         LOC.POPULATION_DENSITY,
         REP.REPORT_NO,
	     REP.INCIDENT_TIME,
         REP.COMPLAINT_TYPE,
         REP.CCTV_FLAG,
         REP.CRIME_CODE,
         REP.CRIME_TYPE,
         REP.CASE_STATUS_CODE,
         REP.CASE_STATUS_DESC,
         REP.WEEK_NUMBER,
		 OFFI.OFFICER_CODE,
         OFFI.PRECINCT_CODE
    FROM LOCATION_T LOC
        JOIN REPORT_T REP ON 
            LOC.AREA_CODE = REP.AREA_CODE
		JOIN OFFICER_T OFFI ON
        REP.OFFICER_CODE= OFFI.OFFICER_CODE;
    