DELIMITER $$
CREATE PROCEDURE REPORT_P(WEEKNUM INTEGER)
BEGIN
	INSERT INTO REPORT_T (
		REPORT_NO,
		INCIDENT_TIME,
        COMPLAINT_TYPE,
        CCTV_FLAG,
        AREA_CODE,
	    VICTIM_CODE,
	    OFFICER_CODE,
        OFFENDER_CODE,
        OFFENDER_NAME,
        OFFENDER_AGE,
        OFFENDER_SEX,
        REPEATED_OFFENDER,
        NO_OF_OFFENCES,
        OFFENDER_RELATION,
        CRIME_CODE,
        CRIME_TYPE,
        WEAPON_CODE,
        WEAPON_DESC,
        CASE_STATUS_CODE,
        CASE_STATUS_DESC,
        WEEK_NUMBER
	) 
    SELECT DISTINCT
	    REPORT_NO,
		INCIDENT_TIME,
        COMPLAINT_TYPE,
        CCTV_FLAG,
        AREA_CODE,
	    VICTIM_CODE,
	    OFFICER_CODE,
        OFFENDER_CODE,
        OFFENDER_NAME,
        OFFENDER_AGE,
        OFFENDER_SEX,
        REPEATED_OFFENDER,
        NO_OF_OFFENCES,
        OFFENDER_RELATION,
        CRIME_CODE,
        CRIME_TYPE,
        WEAPON_CODE,
        WEAPON_DESC,
        CASE_STATUS_CODE,
        CASE_STATUS_DESC,
        WEEK_NUMBER
	FROM CRIME_T WHERE WEEK_NUMBER = WEEKNUM;
END;

-- CALL REPORT_P(1);
