DELIMITER $$
CREATE PROCEDURE VICTIM_P()
BEGIN
    INSERT INTO VICTIM_T (
        VICTIM_CODE,
        VICTIM_NAME,
        VICTIM_AGE,
        VICTIM_SEX,
        WAS_VICTIM_ALONE,
        IS_VICTIM_INSURED
	) 
    SELECT DISTINCT 
	    VICTIM_CODE,
        VICTIM_NAME,
        VICTIM_AGE,
        VICTIM_SEX,
        WAS_VICTIM_ALONE,
        IS_VICTIM_INSURED
	FROM CRIME_T WHERE  VICTIM_CODE NOT IN (SELECT DISTINCT  VICTIM_CODE FROM VICTIM_T);
END;

-- CALL VICTIM_P();
