CREATE TABLE VICTIM_T (
   VICTIM_CODE INTEGER,
   VICTIM_NAME VARCHAR(20),
   VICTIM_AGE INTEGER,
   VICTIM_SEX CHAR(1),
   WAS_VICTIM_ALONE VARCHAR(3),
   IS_VICTIM_INSURED VARCHAR(3),
   PRIMARY KEY ( VICTIM_CODE)
);